# Generated by Django 5.2.14 on 2026-06-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='Book_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
