# Generated by Django 5.2.14 on 2026-06-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_city_student_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Author',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Book_id',
            new_name='Student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='price',
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
