# Generated by Django 5.2.14 on 2026-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_author_student_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_id',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=90, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=90, max_length=15),
            preserve_default=False,
        ),
    ]
